version: '3.8'

services:
  kdhome:
    build: .
    ports:
      - "8888:80"
    container_name: kunaldawn-homepage
    restart: unless-stopped
    networks:
      - web

networks:
  web:
    driver: bridge
