services:
  kdhome:
    build: .
    ports:
      - "8888:8080"
    container_name: kunaldawn-homepage
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    networks:
      - web

networks:
  web:
    driver: bridge
